# Generated by Django 5.1.4 on 2025-01-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.hostitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
    ]
