# Generated by Django 5.1.4 on 2025-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
